name: Deploy app

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: demo
      url: ${{ steps.deploy_to_pages.outputs.github_pages_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Vite Github Pages Deployer
        uses: skywarth/vite-github-pages-deployer@v1.3.0
        id: deploy_to_pages

      - name: dump outputs
        run:  echo "${{steps.deploy_to_pages.outputs.github_pages_url}}"
